import type { ResumeAnalysisResult } from '@/lib/gemini';

export function buildResumeAnalysisMarkdown(jobRole: string, result: ResumeAnalysisResult): string {
  const lines = [
    `# Resume analysis — ${jobRole}`,
    '',
    `**Score:** ${result.score.toFixed(1)} / 10`,
    '',
    '## Summary',
    '',
    result.summary,
    '',
    '## Strengths',
    '',
    ...result.strengths.map((s) => `- ${s}`),
    '',
    '## Improvements',
    '',
    ...(result.improvements ?? []).map((s) => `- ${s}`),
    '',
    '## Interview tips',
    '',
    ...(result.tips ?? []).map((s) => `- ${s}`),
    '',
  ];
  if (result.matchLabel) lines.push(`**Match:** ${result.matchLabel}`, '');
  if (result.percentileLabel) lines.push(`**Benchmark:** ${result.percentileLabel}`, '');
  lines.push('---', '*Generated by AI Career Assistant*');
  return lines.join('\n');
}

export function downloadTextFile(filename: string, body: string, mime = 'text/plain;charset=utf-8'): void {
  const blob = new Blob([body], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.rel = 'noopener';
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function openPrintableAnalysis(jobRole: string, result: ResumeAnalysisResult): void {
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Resume analysis — ${escapeHtml(jobRole)}</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 24px; max-width: 720px; margin: 0 auto; color: #0f172a; }
    h1 { font-size: 1.5rem; }
    h2 { font-size: 1.1rem; margin-top: 1.25rem; }
    .score { font-size: 2rem; font-weight: 700; color: #6d28d9; }
    ul { padding-left: 1.25rem; }
    li { margin: 0.35rem 0; }
    @media print { body { padding: 12px; } }
  </style></head><body>
  <h1>Resume analysis — ${escapeHtml(jobRole)}</h1>
  <p class="score">${result.score.toFixed(1)} / 10</p>
  <h2>Summary</h2><p>${escapeHtml(result.summary)}</p>
  <h2>Strengths</h2><ul>${result.strengths.map((s) => `<li>${escapeHtml(s)}</li>`).join('')}</ul>
  <h2>Improvements</h2><ul>${(result.improvements ?? []).map((s) => `<li>${escapeHtml(s)}</li>`).join('')}</ul>
  <h2>Interview tips</h2><ul>${(result.tips ?? []).map((s) => `<li>${escapeHtml(s)}</li>`).join('')}</ul>
  ${result.matchLabel ? `<p><strong>Match:</strong> ${escapeHtml(result.matchLabel)}</p>` : ''}
  ${result.percentileLabel ? `<p><strong>Benchmark:</strong> ${escapeHtml(result.percentileLabel)}</p>` : ''}
  <p style="margin-top:2rem;color:#64748b;font-size:12px;">AI Career Assistant — use Print → Save as PDF</p>
  </body></html>`;
  const w = window.open('', '_blank', 'noopener,noreferrer');
  if (w) {
    w.document.open();
    w.document.write(html);
    w.document.close();
    window.setTimeout(() => {
      w.focus();
      w.print();
    }, 350);
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
